api_login:
    path: /api/login
    methods: [POST]

logout:
    path: /logout

index:
    path: /
    controller: MarioDevment\ApiUser\Infrastructure\Symfony\Controller\DefaultController::__invoke

api_context:
    path: /api
    controller: MarioDevment\ApiUser\Context\Users\Infrastructure\LoginController::loginSuccess